"""
Constantes de la aplicación CyberWatch
"""

# Seguridad y autenticación
BCRYPT_MAX_PASSWORD_LENGTH = 72
SESSION_COOKIE_MAX_AGE = 3600  # 1 hora

# Paginación
PAGINATION_OPTIONS = [10, 25, 100]
DEFAULT_PER_PAGE = 25

# Límites de tamaño
MAX_LOG_FILE_SIZE = 1_000_000  # 1MB en caracteres
MAX_FILENAME_LENGTH = 255
MAX_EMAIL_LENGTH = 255
MAX_PASSWORD_LENGTH = 255
MAX_FULLNAME_LENGTH = 200
MAX_INCIDENT_TITLE_LENGTH = 200
MAX_INCIDENT_DESCRIPTION_LENGTH = 5000
MAX_INCIDENT_CODE_LENGTH = 50

# Rate limiting
LOGIN_RATE_LIMIT = "5/minute"
INCIDENT_CREATE_RATE_LIMIT = "10/minute"
FILE_UPLOAD_RATE_LIMIT = "5/minute"
