AWSTemplateFormatVersion: '2010-09-09'
Description: 'CyberWatch - Sistema de Gestion de Incidentes de Seguridad'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nombre del Key Pair existente para SSH
    ConstraintDescription: Debe ser un Key Pair existente en tu cuenta AWS
  
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    Description: Tipo de instancia EC2 (t2.micro es Free Tier)
  
  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    Description: IP permitida para SSH (usa tu IP publica para mayor seguridad)
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Debe ser un CIDR valido (ej. 203.0.113.0/24)

Resources:
  # Security Group
  CyberWatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: cyberwatch-sg
      GroupDescription: Security group para CyberWatch
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS access
      Tags:
        - Key: Name
          Value: cyberwatch-sg
        - Key: Project
          Value: CyberWatch

  # Elastic IP
  CyberWatchEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: cyberwatch-eip
        - Key: Project
          Value: CyberWatch

  # Asociar EIP a instancia
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref CyberWatchEC2Instance
      EIP: !Ref CyberWatchEIP

  # Instancia EC2
  CyberWatchEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref CyberWatchSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 10
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Logging
          exec > >(tee /var/log/user-data.log)
          exec 2>&1
          
          echo "=== Iniciando configuracion de CyberWatch ==="
          
          # Actualizar sistema
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
          
          # Instalar dependencias
          apt-get install -y \
            python3 \
            python3-pip \
            python3-venv \
            nginx \
            git \
            curl \
            unzip
          
          # Crear usuario de aplicacion
          useradd -m -s /bin/bash cyberwatch || true
          
          # Crear directorio de aplicacion
          mkdir -p /opt/cyberwatch
          chown cyberwatch:cyberwatch /opt/cyberwatch
          
          # Instalar dependencias Python globalmente
          pip3 install --upgrade pip
          pip3 install \
            fastapi==0.115.5 \
            uvicorn[standard]==0.32.1 \
            sqlmodel==0.0.22 \
            passlib[bcrypt]==1.7.4 \
            python-multipart==0.0.20 \
            jinja2==3.1.4 \
            slowapi==0.1.9
          
          # Configurar Nginx
          cat > /etc/nginx/sites-available/cyberwatch <<'NGINX_EOF'
          server {
              listen 80;
              server_name _;
          
              client_max_body_size 10M;
          
              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_read_timeout 300s;
                  proxy_connect_timeout 75s;
              }
          
              location /static {
                  alias /opt/cyberwatch/app/frontend/static;
                  expires 30d;
                  add_header Cache-Control "public, immutable";
              }
          }
          NGINX_EOF
          
          # Activar configuracion Nginx
          ln -sf /etc/nginx/sites-available/cyberwatch /etc/nginx/sites-enabled/
          rm -f /etc/nginx/sites-enabled/default
          nginx -t && systemctl restart nginx
          
          # Crear servicio systemd
          cat > /etc/systemd/system/cyberwatch.service <<'SYSTEMD_EOF'
          [Unit]
          Description=CyberWatch FastAPI Application
          After=network.target
          
          [Service]
          Type=simple
          User=cyberwatch
          WorkingDirectory=/opt/cyberwatch
          ExecStart=/usr/local/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
          Restart=always
          RestartSec=3
          StandardOutput=append:/var/log/cyberwatch/app.log
          StandardError=append:/var/log/cyberwatch/error.log
          
          [Install]
          WantedBy=multi-user.target
          SYSTEMD_EOF
          
          # Crear directorio de logs
          mkdir -p /var/log/cyberwatch
          chown cyberwatch:cyberwatch /var/log/cyberwatch
          
          # Habilitar servicio (se iniciara cuando se suba el codigo)
          systemctl daemon-reload
          systemctl enable cyberwatch
          
          # Configurar firewall
          ufw allow 22/tcp
          ufw allow 80/tcp
          ufw allow 443/tcp
          ufw --force enable
          
          # Crear script de deploy
          cat > /opt/deploy-cyberwatch.sh <<'DEPLOY_EOF'
          #!/bin/bash
          cd /opt/cyberwatch
          chown -R cyberwatch:cyberwatch /opt/cyberwatch
          chmod 644 cyberwatch.db 2>/dev/null || true
          systemctl restart cyberwatch
          systemctl status cyberwatch
          DEPLOY_EOF
          
          chmod +x /opt/deploy-cyberwatch.sh
          
          # Mensaje de finalizacion
          echo "=== Configuracion base completada ==="
          echo "Esperando que se suba el codigo de la aplicacion..."
          echo "Una vez subido, ejecutar: sudo /opt/deploy-cyberwatch.sh"
          
      Tags:
        - Key: Name
          Value: cyberwatch-server
        - Key: Project
          Value: CyberWatch

Mappings:
  # AMI IDs de Ubuntu 22.04 LTS por region
  RegionMap:
    us-east-1:
      AMI: ami-0c7217cdde317cfec
    us-east-2:
      AMI: ami-0a695f0d95cefc163
    us-west-1:
      AMI: ami-0ce2cb35386fc22e9
    us-west-2:
      AMI: ami-0b8c6b923777519db
    eu-west-1:
      AMI: ami-0905a3c97561e0b69
    eu-central-1:
      AMI: ami-0faab6bdbac9486fb
    ap-southeast-1:
      AMI: ami-0c802847a7dd848c0
    ap-northeast-1:
      AMI: ami-0d52744d6551d851e

Outputs:
  PublicIP:
    Description: IP publica elastica de CyberWatch
    Value: !Ref CyberWatchEIP
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'
  
  WebsiteURL:
    Description: URL de acceso a CyberWatch
    Value: !Sub 'http://${CyberWatchEIP}'
  
  SSHCommand:
    Description: Comando para conectar por SSH
    Value: !Sub 'ssh -i ~/.ssh/${KeyName}.pem ubuntu@${CyberWatchEIP}'
  
  DeployCommand:
    Description: Comando para subir el codigo
    Value: !Sub 'scp -i ~/.ssh/${KeyName}.pem -r * ubuntu@${CyberWatchEIP}:/opt/cyberwatch/'
