from datetime import datetime, timedelta, timezone

from sqlmodel import Session, select

from app.backend.database import engine, init_db
from app.backend.models import Incident


def seed_incidents():
    init_db()
    now = datetime.now(timezone.utc)

    demo_incidents = [
        {
            "code": "INC-2025-0012",
            "title": "Ransomware detectado en servidor de archivos",
            "severity": "Crítico",
            "status": "En investigación",
            "source": "EDR",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(minutes=40),
            "updated_at": now - timedelta(minutes=5),
            "description": "Detección de cifrado masivo en volumen compartido.",
        },
        {
            "code": "INC-2025-0011",
            "title": "Escaneo de puertos desde IP externa",
            "severity": "Alto",
            "status": "Abierto",
            "source": "Firewall",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(hours=2),
            "updated_at": now - timedelta(minutes=35),
            "description": "Escaneo intensivo contra servicios expuestos.",
        },
        {
            "code": "INC-2025-0010",
            "title": "Múltiples intentos de login fallidos",
            "severity": "Medio",
            "status": "Monitorizando",
            "source": "SIEM",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(hours=4),
            "updated_at": now - timedelta(hours=1),
            "description": "Actividad sospechosa en portal VPN.",
        },
        {
            "code": "INC-2025-0009",
            "title": "Campaña de phishing reportada por usuarios",
            "severity": "Medio",
            "status": "Abierto",
            "source": "Correo",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=1, hours=3),
            "updated_at": now - timedelta(days=1, hours=1),
            "description": "Correos fraudulentos simulando al equipo de IT.",
        },
        {
            "code": "INC-2025-0008",
            "title": "Actividad anómala en base de datos de clientes",
            "severity": "Alto",
            "status": "En investigación",
            "source": "BD Audit",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(hours=6),
            "updated_at": now - timedelta(hours=5, minutes=15),
            "description": "Consultas masivas fuera de horario sobre tabla de clientes.",
        },
        {
            "code": "INC-2025-0007",
            "title": "Sesión VPN desde país no habitual",
            "severity": "Medio",
            "status": "Abierto",
            "source": "VPN",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(hours=7, minutes=30),
            "updated_at": now - timedelta(hours=6, minutes=50),
            "description": "Conexión VPN con geolocalización fuera de los países permitidos.",
        },
        {
            "code": "INC-2025-0006",
            "title": "Bloqueo masivo de correos por posible phishing",
            "severity": "Alto",
            "status": "Monitorizando",
            "source": "Correo",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(hours=9),
            "updated_at": now - timedelta(hours=8, minutes=20),
            "description": "Incremento de correos con links a dominios recién registrados.",
        },
        {
            "code": "INC-2025-0005",
            "title": "Intentos de explotación de vulnerabilidad web",
            "severity": "Crítico",
            "status": "Abierto",
            "source": "WAF",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(hours=10),
            "updated_at": now - timedelta(hours=9, minutes=10),
            "description": "Múltiples payloads asociados a CVE críticas en aplicación externa.",
        },
        {
            "code": "INC-2025-0004",
            "title": "Usuario con privilegios elevando permisos",
            "severity": "Medio",
            "status": "En investigación",
            "source": "IAM",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(hours=12),
            "updated_at": now - timedelta(hours=11, minutes=40),
            "description": "Cambios de rol repetidos en intervalo corto sobre el mismo usuario.",
        },
        {
            "code": "INC-2025-0003",
            "title": "Alerta de beaconing hacia dominio sospechoso",
            "severity": "Crítico",
            "status": "Monitorizando",
            "source": "Proxy",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(hours=16),
            "updated_at": now - timedelta(hours=15, minutes=30),
            "description": "Tráfico periódico de pequeño volumen hacia dominio categorizado como malware.",
        },
        {
            "code": "INC-2025-0002",
            "title": "Actividad de escaneo interno de red",
            "severity": "Alto",
            "status": "Abierto",
            "source": "Red",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(days=2, hours=5),
            "updated_at": now - timedelta(days=2, hours=3),
            "description": "Escaneo entre segmentos internos desde host de usuario.",
        },
        {
            "code": "INC-2025-0001",
            "title": "Detección de aplicación no autorizada en endpoint",
            "severity": "Bajo",
            "status": "Abierto",
            "source": "Endpoint",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=3, hours=2),
            "updated_at": now - timedelta(days=3, hours=1),
            "description": "Instalación de software no aprobado por catálogo corporativo.",
        },
        {
            "code": "INC-2024-0123",
            "title": "Conexiones salientes hacia TOR detectadas",
            "severity": "Crítico",
            "status": "En investigación",
            "source": "Firewall",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(days=5, hours=3),
            "updated_at": now - timedelta(days=5, hours=2),
            "description": "Tráfico hacia nodos de salida TOR desde estación de trabajo.",
        },
        {
            "code": "INC-2024-0122",
            "title": "Incremento de errores de autenticación en SSO",
            "severity": "Medio",
            "status": "Monitorizando",
            "source": "SSO",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(days=6, hours=1),
            "updated_at": now - timedelta(days=6),
            "description": "Posibles ataques de password spraying sobre el portal SSO.",
        },
        {
            "code": "INC-2024-0121",
            "title": "Transferencias de datos inusuales a almacenamiento cloud",
            "severity": "Alto",
            "status": "En Investigación",
            "source": "CASB",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=7, hours=4),
            "updated_at": now - timedelta(days=7, hours=3),
            "description": "Subida masiva de ficheros desde red interna a almacenamiento externo.",
        },
        {
            "code": "INC-2024-0120",
            "title": "Puerto administrativo expuesto en servidor crítico",
            "severity": "Bajo",
            "status": "Abierto",
            "source": "Scanner",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(days=10),
            "updated_at": now - timedelta(days=9, hours=20),
            "description": "Puerto de administración accesible desde redes no autorizadas.",
        },

        {
            "code": "INC-2025-0013",
            "title": "Detección de malware en estación de trabajo",
            "severity": "Alto",
            "status": "En investigación",
            "source": "EDR",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(minutes=20),
            "updated_at": now - timedelta(minutes=10),
            "description": "Archivo ejecutable malicioso puesto en cuarentena en equipo de usuario.",
        },
        {
            "code": "INC-2025-0014",
            "title": "Tráfico anómalo hacia API externa",
            "severity": "Medio",
            "status": "Monitorizando",
            "source": "Proxy",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(hours=3, minutes=15),
            "updated_at": now - timedelta(hours=2, minutes=40),
            "description": "Volumen inusual de peticiones desde un único cliente hacia API de terceros.",
        },
        {
            "code": "INC-2025-0015",
            "title": "Accessos sospechosos al panel de administración",
            "severity": "Crítico",
            "status": "Abierto",
            "source": "WAF",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(hours=1, minutes=5),
            "updated_at": now - timedelta(minutes=25),
            "description": "Múltiples intentos de acceso con parámetros anómalos en panel administrativo.",
        },
        {
            "code": "INC-2025-0016",
            "title": "Cambios de configuración en firewall no autorizados",
            "severity": "Alto",
            "status": "En investigación",
            "source": "Firewall",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(hours=5, minutes=30),
            "updated_at": now - timedelta(hours=4, minutes=50),
            "description": "Reglas de firewall modificadas fuera de la ventana de cambio.",
        },
        {
            "code": "INC-2025-0017",
            "title": "Alertas de DLP por fuga de datos potencial",
            "severity": "Crítico",
            "status": "Monitorizando",
            "source": "DLP",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(hours=8),
            "updated_at": now - timedelta(hours=7, minutes=20),
            "description": "Detección de documentos sensibles adjuntos en correo saliente.",
        },
        {
            "code": "INC-2025-0018",
            "title": "Actividad anómala en consola cloud",
            "severity": "Medio",
            "status": "Abierto",
            "source": "Cloud",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(hours=6, minutes=10),
            "updated_at": now - timedelta(hours=5, minutes=40),
            "description": "Creación de recursos en regiones no utilizadas habitualmente.",
        },
        {
            "code": "INC-2025-0019",
            "title": "Escaneo de puertos internos detectado por NIDS",
            "severity": "Alto",
            "status": "Monitorizando",
            "source": "NIDS",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(hours=11),
            "updated_at": now - timedelta(hours=10, minutes=30),
            "description": "Escaneo lateral desde host comprometido hacia subred interna.",
        },
        {
            "code": "INC-2025-0020",
            "title": "Descarga masiva de logs desde servidor SIEM",
            "severity": "Medio",
            "status": "En investigación",
            "source": "SIEM",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(hours=9, minutes=45),
            "updated_at": now - timedelta(hours=9, minutes=5),
            "description": "Descarga inesperada de grandes volúmenes de logs por usuario privilegiado.",
        },
        {
            "code": "INC-2025-0021",
            "title": "Incremento de errores 401 en portal VPN",
            "severity": "Bajo",
            "status": "Monitorizando",
            "source": "VPN",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(hours=3),
            "updated_at": now - timedelta(hours=2, minutes=10),
            "description": "Posible intento de password spraying de baja intensidad.",
        },
        {
            "code": "INC-2025-0022",
            "title": "Exfiltración potencial a servicio de almacenamiento personal",
            "severity": "Crítico",
            "status": "Abierto",
            "source": "CASB",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(days=1, hours=6),
            "updated_at": now - timedelta(days=1, hours=5, minutes=30),
            "description": "Usuarios subiendo ficheros de proyectos críticos a cuentas personales.",
        },
        {
            "code": "INC-2025-0023",
            "title": "Conexiones SSH desde IP no listada",
            "severity": "Medio",
            "status": "En investigación",
            "source": "Red",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=1, hours=1),
            "updated_at": now - timedelta(hours=20),
            "description": "Sesiones SSH iniciadas desde rangos de IP externos no habituales.",
        },
        {
            "code": "INC-2025-0024",
            "title": "Picos de CPU por proceso desconocido en servidor crítico",
            "severity": "Alto",
            "status": "En investigación",
            "source": "Endpoint",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(days=2, hours=2),
            "updated_at": now - timedelta(days=2, hours=1, minutes=15),
            "description": "Proceso no inventariado consumiendo recursos en servidor productivo.",
        },
        {
            "code": "INC-2025-0025",
            "title": "Dispositivo USB no autorizado conectado",
            "severity": "Bajo",
            "status": "Abierto",
            "source": "Endpoint",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=2, hours=8),
            "updated_at": now - timedelta(days=2, hours=7, minutes=45),
            "description": "Uso de dispositivo USB sin cifrar en puesto de trabajo.",
        },
        {
            "code": "INC-2024-0119",
            "title": "Múltiples fallos de autenticación en base de datos",
            "severity": "Medio",
            "status": "Monitorizando",
            "source": "BD Audit",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(days=8, hours=5),
            "updated_at": now - timedelta(days=8, hours=4, minutes=20),
            "description": "Credenciales incorrectas repetidas desde misma aplicación.",
        },
        {
            "code": "INC-2024-0118",
            "title": "Intentos de acceso a recurso legacy desmantelado",
            "severity": "Bajo",
            "status": "Abierto",
            "source": "Red",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=9, hours=3),
            "updated_at": now - timedelta(days=9, hours=2, minutes=40),
            "description": "Sondeos periódicos a un hostname ya retirado.",
        },
        {
            "code": "INC-2024-0117",
            "title": "Subida de binarios sospechosos a repositorio interno",
            "severity": "Alto",
            "status": "En investigación",
            "source": "Cloud",
            "owner": "Analista Nivel 3",
            "detected_at": now - timedelta(days=4, hours=6),
            "updated_at": now - timedelta(days=4, hours=5, minutes=10),
            "description": "Artefactos no firmados detectados en repositorio de artefactos.",
        },
        {
            "code": "INC-2024-0116",
            "title": "Alertas de NIDS por exploración de puertos",
            "severity": "Medio",
            "status": "Monitorizando",
            "source": "NIDS",
            "owner": "Analista Nivel 2",
            "detected_at": now - timedelta(days=3, hours=10),
            "updated_at": now - timedelta(days=3, hours=9, minutes=50),
            "description": "Exploración horizontal entre varios segmentos internos.",
        },
        {
            "code": "INC-2024-0115",
            "title": "Inicios de sesión desde dispositivo no gestionado",
            "severity": "Alto",
            "status": "En investigación",
            "source": "SSO",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=6, hours=7),
            "updated_at": now - timedelta(days=6, hours=6, minutes=15),
            "description": "Logins válidos desde equipos sin agente corporativo.",
        },
        {
            "code": "INC-2024-0114",
            "title": "Acceso a share compartido fuera de horario laboral",
            "severity": "Bajo",
            "status": "Abierto",
            "source": "BD Audit",
            "owner": "Analista Nivel 1",
            "detected_at": now - timedelta(days=5, hours=23),
            "updated_at": now - timedelta(days=5, hours=22, minutes=30),
            "description": "Lecturas de ficheros sensibles a medianoche por usuario interno.",
        },
    ]

    with Session(engine) as session:
        for data in demo_incidents:
            existing = session.exec(
                select(Incident).where(Incident.code == data["code"])
            ).first()
            if existing:
                continue
            incident = Incident(**data)
            session.add(incident)
        session.commit()


if __name__ == "__main__":
    seed_incidents()
